// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEADvE-P4JXV-ZwrXp5FCnYvNM_TiMR_A',
    appId: '1:370084007343:android:25ba2f4518ed2fd0cd335a',
    messagingSenderId: '370084007343',
    projectId: 'fluechat-3f628',
    storageBucket: 'fluechat-3f628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2-r4TS_8oPm0_PLXJWvWQfivJJCGv6c',
    appId: '1:370084007343:ios:b672d64045c13c8ccd335a',
    messagingSenderId: '370084007343',
    projectId: 'fluechat-3f628',
    storageBucket: 'fluechat-3f628.appspot.com',
    iosClientId: '370084007343-1eifvfagp34geoktff6lmvh5gji77ihr.apps.googleusercontent.com',
    iosBundleId: 'flue.app',
  );
}
