// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF1UgsG6gGcgjWw_wleX9DiIbtk4qpfrY',
    appId: '1:572844474818:android:2f6b14c0d5265a57ac165b',
    messagingSenderId: '572844474818',
    projectId: 'fluefire',
    storageBucket: 'fluefire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMToI5wSXvFF9e8OuIn19Jj8zv9fE_eGU',
    appId: '1:572844474818:ios:e988169fabd1ec1aac165b',
    messagingSenderId: '572844474818',
    projectId: 'fluefire',
    storageBucket: 'fluefire.appspot.com',
    androidClientId: '572844474818-86ftca0bn231hjlok89p5pe3i0lkmskl.apps.googleusercontent.com',
    iosClientId: '572844474818-ai91ojma60s6nq3aei6dkf90hfm3m36d.apps.googleusercontent.com',
    iosBundleId: 'flue.app',
  );
}
